### ISSUE TITLE
add i18n with Transifex

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#1]
The Project is already available under www.transifex.com/cstenglein/raspiblitz-web but it needs language sources files to be added, as well as integration in the project (dependency already added)

**Comment by comradekingu** [comment]
Consider using Weblate instead. Libre software, no spying, better interface and resulting translations.

**Comment by cstenglein** [comment]
Hi @comradekingu 

Thanks for the suggestion. Unfortunately I am not able to get weblate working. It is not extracting the values for the translation and instead uses the keys as translation target, see https://hosted.weblate.org/projects/raspiblitz-web/translations/

I will try it again in the coming days and if I don't get it done, I'll use Transifex since it works out of the box.

**Comment by comradekingu** [comment]
@cstenglein That seems like a config error
If you add https://hosted.weblate.org/user/kingu/ in https://hosted.weblate.org/access/raspiblitz-web/#users I can have a look.

**Comment by cstenglein** [comment]
Thank you for your help @comradekingu , added you :)

Yeah I think that as well :/

**Comment by cstenglein** [comment]
@comradekingu Got it working with a test component, thank you so much!

Will delete both components and redo again correctly; I thought I have to upload the files automatically :O

**Comment by cstenglein** [comment]
Translations can now be found under https://hosted.weblate.org/projects/raspiblitz-web/translations/
Also linked in the README

Thanks again @comradekingu  :)

**Comment by comradekingu** [comment]
All you :) I added a push address in 
https://hosted.weblate.org/settings/raspiblitz-web/translations/#vcs and a template file for new translations in https://hosted.weblate.org/settings/raspiblitz-web/translations/#files
and opened the WL component.

If the nb_NO strings make their way here, it works.

I think https://docs.weblate.org/no/latest/admin/continuous.html?highlight=contin#automatically-receiving-changes-from-github is needed, and maybe https://github.com/weblate added to the organization.

**Comment by cstenglein** [comment]
@comradekingu it works now, thank you very much! :)

Adding Weblate as a collaborator was the missing piece ;)
