### ISSUE TITLE
Clipboard does not work on HTTP connection when using local IP

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#109]
See https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by escapedcat** [comment]
Would it be possible/wanted to somehow switch to/support https?

**Comment by cstenglein** [comment]
The problem with https locally is that you have to use a self-signed certificate, which triggers a warning screen in chrome / FF.

We decided to use http but show a warning in the login screen to use the tor hidden service & that http is not encrypted traffic.

For the clipboard, we can use a workaround: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
