### ISSUE TITLE
ConfirmDialog: Add Input for amount if invoice amount was 0 sat

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#127]
E.g. [Muun](https://muun.com) creates 0 sat invoices by default.

If the decoded invoice was 0 sat, show an amountinput with a note that you need to enter an amount.

**Comment by escapedcat** [comment]
Can you post an invoice example with 0 sats? Don't know how to create one X_x

**Comment by cstenglein** [comment]
Doesn't look like you can create one with Polar, but you can with the blitz_api or lnd api direcly:

There you go:
`lnbcrt1ps6hyqqpp5shls2yek2mxvm9seek8yl4w2c0jts0j63u7sanl6geqgf72ndhvsdq8w3jhxaqcqzpgxqrrsssp5xpvyhfe0euruhvj99cseczh5jfh75nxeu4vmfdexxfa4068jtp7q9qyyssqpmjdulnu6nh8nj2njhqkdhurf36042k4knx75yu4nm75m4g770pq6ahv66l8tp7weed6vte3k9axjqn2s4yceppthtr79xtgg3wdgfsqn2lz6k`
