### ISSUE TITLE
Change "Display SATS" toggle name

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#135]
~~Idea: Remove that toggle and in Settings, create a dropdown where you can switch between denominations (sat / btc)~~

Rename "Display SATS" to something more fitting

**Comment by escapedcat** [comment]
What's the reasoning behind this?

**Comment by cstenglein** [comment]
Was from a review meeting with freerk in El Salvador.

Reasoning was (as far as I remember) I don't really need to change the denomination it that much.

Other wallets have some settings for denomination in the settings dialog, so we could do something like this as well.

The Dark Mode Moon Icon could be on the upper right corner, like with the login screen.

**Comment by escapedcat** [comment]
Got it, will be moved into **settings**.   
That means we would also get rid of the switch in the AmountInput, yes? I support this :)  

Who's freerk? 😊

**Comment by cstenglein** [comment]
If you want to work on that, the following things need so be done:

- Replace the dropdown menu with the moon icon (same functionality as login screen)
- add a dropdown to the settings menu where the user can set their denomination (default is sats)

> Who's freerk

See twitter DM ;)

**Comment by escapedcat** [comment]
> Reasoning was (as far as I remember) I don't really need to change the denomination it that much.
> Other wallets have some settings for denomination in the settings dialog, so we could do something like this as well.

Had another look at i.e. [Samourai wallet](https://samouraiwallet.com/) and [BlueWallet](https://bluewallet.io/). Both offer a switch like it's currently implemented now.  
What speaks against leaving this for now?  

Happy to move/align the dark-mode icon although I believe this shoudl be handled in a different issue.

**Comment by cstenglein** [comment]
...

Okay, know I know what was wrong: The "Display SATS" is kinda confusing for people I think.

Keep the dropdown and stuff, let's just change "Display SATS" to something more fitting so people realize they can change it to another denomination.

Maybe a label on top with the two sides on the toggle? 

---

Denomination:
SAT <toggle> BTC

---

Thank you for the really awesome input! :heart:

**Comment by cstenglein** [comment]
Currently leaving "as-is" => closed
