### ISSUE TITLE
calculate difficulty correctly

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#169]

**Comment by escapedcat** [comment]
Can haz morrrrrrr detailz? :P

**Comment by cstenglein** [comment]
Currently the difficulty has "TH" hardcoded in it:

![image](https://user-images.githubusercontent.com/9399034/150652023-83349dd3-b679-4c0a-b76d-e4bad86221ad.png)

https://github.com/cstenglein/raspiblitz-web/blob/master/src/components/Home/BitcoinCard/BitcoinCard.tsx#L34

I'm not even sure if I calculate that correctly, thus I created this issue. :)

**Comment by cstenglein** [comment]
How it is calculated by mempool:

https://github.com/mempool/mempool/blob/master/frontend/src/app/components/difficulty/difficulty.component.ts

Something like this would be the correct way. Visualization by mempool:

![image](https://user-images.githubusercontent.com/9399034/155883999-30337c1b-52e7-4fe3-bc67-5c36aafb2394.png)

**Comment by cstenglein** [comment]
Closed for now - will be replaced by "blocktime" and maybe done at a later point in time
