### ISSUE TITLE
Research: Make backend connectionstatus (top right) more clear & update correctly

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#210]
Currently there is an icon on the top right which is indicating the connection status:

![image](https://user-images.githubusercontent.com/9399034/156635867-b1c62e2e-b4dd-44f6-b4ac-8113c2211153.png)

This currently has some issues:

- it doesn't update correctly
- the user doesn't know what it means

=> Think about how to make it clear that it is the connection to the backend. Could also be transformed to a status / health icon (maybe for a tooltip menu which displays stuff like app installing etc?)

**Comment by escapedcat** [comment]
> * it doesn't update correctly

You have an idea when this is the case?

> * the user doesn't know what it means
> 
> => Think about how to make it clear that it is the connection to the backend. Could also be transformed to a status / health icon (maybe for a tooltip menu which displays stuff like app installing etc?)

Maybe let's go for a clearer icon first and expand to something bigger when needed?  
Could imagine combining the icon with a label or a tooltip might work already. What do you think?

**Comment by cstenglein** [comment]
> You have an idea when this is the case?

The object is forwarded as input to the component and not the values. The object doesn't update => no change in the component.

> Maybe let's go for a clearer icon first and expand to something bigger when needed?
Could imagine combining the icon with a label or a tooltip might work already. What do you think?

Don't know yet. This is a Research issue after all :)
