### ISSUE TITLE
Improve dark mode colors

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#211]
Some contrasts are really inconsistent and hard to differentiate

**Comment by escapedcat** [comment]
Some screenshots of bad examples would be great

**Comment by cstenglein** [comment]
Modal blur has not enough contrast for dark mode + in these examples the gray button too light & the background of the modal dialog is also too light:
![ex1](https://user-images.githubusercontent.com/9399034/156882401-7c64b261-689b-467c-a6f0-0f5b5cd3362a.png)
![ex2](https://user-images.githubusercontent.com/9399034/156882403-75f1f0b7-1e21-4f7d-8b5d-da58119ef342.png)

Gray buttons here are better but don't know if they should be even darker, same for orange:
![ex3](https://user-images.githubusercontent.com/9399034/156882406-d83688e3-5a5e-4a64-85a1-4b25613f7bba.png)

Not a UX Expert tough, just my feelings.

**Comment by cstenglein** [comment]
In addiiton, the "black" buttons in Home (Send/Receive) are too dark in dark mode => need to be lighter.
