### ISSUE TITLE
check qr code to pay a lightning invoice

### ISSUE THREAD

**Issue by rootzoll** [cstenglein/raspiblitz-web#231]
The QR code generated in my test did not work with zeus, wos or even a generic qr code scanner app. To be retested.

Also it says "Fund your on-chain wallet" when showing my the lightning invoice. To be checked if wrong translation key is used.

**Comment by cstenglein** [comment]
Got a new SSD, so I will be able to check as well in the coming days on a real RaspiBlitz.

**Comment by cstenglein** [comment]
Justed tested it (blitz_api & raspiblitz-web on master branch) but it works for me (both LN and on-chain receive URL).

Can confirm the "Fund your on-chain wallet" bug though

**Comment by cstenglein** [comment]
@rootzoll could you give more details please? Can't reproduce the error unfortunately.

**Comment by cstenglein** [comment]
Fixed the text bug in #267 
Can't reproduce the other one so I'll close this for now.
