### ISSUE TITLE
Info on what credentials an app needs

### ISSUE THREAD

**Issue by rootzoll** [cstenglein/raspiblitz-web#257]
I added the field `authMethod` to the backend info on the app status. This can be:

- `none` if there is are no credentials needed to open the app
- `userdefined` if the app let the user set its own credentials (like BTCPay)
- `password_b` when just the RaspiBlitz password B is user (like with RTL or ThunderHub)
- `user_admin_password_b` when the user is `admin` and the password B (like with BTC-RPC-Explorer)

This information can be used to display information to the user what credientials to use to to open an app

**Comment by cstenglein** [comment]
See also #253
