### ISSUE TITLE
Layout of Seedwords on Setup

### ISSUE THREAD

**Issue by rootzoll** [cstenglein/raspiblitz-web#258]
The Setup already looks much cleaner .. on thing maybe on a fresh setup would be to layout a bit the seedwords when Setup is finished: 

![Bildschirmfoto 2022-05-03 um 20 46 08](https://user-images.githubusercontent.com/2472225/166521994-b37560e9-79c8-4c9e-95a9-8dd6366e81aa.png)

**Comment by cstenglein** [comment]
Not happy with mobile though. Depending on the length of words, there could be a line break after the number, but should be fine for now.

![image](https://user-images.githubusercontent.com/9399034/166625437-f34a55fe-ba5f-4cdc-bec0-c2c01c2ecd68.png)

![image](https://user-images.githubusercontent.com/9399034/166625458-d41b630c-5c63-4282-8bd8-7ef5e25d322b.png)

![image](https://user-images.githubusercontent.com/9399034/166625483-6e9949ce-0b12-4186-aeab-4b76759d77ef.png)
