### ISSUE TITLE
Prevent jump of input when showing error

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#298]

**Comment by escapedcat** [comment]
Issue can be seen here:\
https://github.com/cstenglein/raspiblitz-web/issues/234#issuecomment-1159374686

How should this be solved? I saw other libraries leave a certain fixed space for "a message", whcih can be a hint or an error.\
Could do the same here I guess. The eror message could also be a bit smaller font-size.

**Comment by cstenglein** [comment]
Yes would add some empty space which would be filled with the error if available.

**Comment by cstenglein** [comment]
Should be fixed AFAIK
