### ISSUE TITLE
AmountInput doesn't work

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#308]
Looks like I broke it

When putting in a value, it doesn't recognize it in the form.

![image](https://user-images.githubusercontent.com/9399034/170917918-d213c572-6e48-46fa-9dc9-b7939fa85cae.png)

**Comment by cstenglein** [comment]
Only if the comma was added => The wrong value is used for validation

**Comment by escapedcat** [comment]
Morrrr tests :)

**Comment by cstenglein** [comment]
Not enough time, as sad as it is. Just pushing out features and hoping I have more later on. :/
