### ISSUE TITLE
test bitcoin-only widget

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#316]
see https://github.com/rootzoll/raspiblitz/issues/3137

**Comment by rootzoll** [comment]
As a quick report ... this is how the WebUI looked when I installed over SSH a fresh bitcoin-only RaspiBlitz:
![Bildschirmfoto 2022-06-04 um 16 46 38](https://user-images.githubusercontent.com/2472225/172008355-fb28be0b-8dff-4be1-8337-b297c123ace1.png)

like you see with the networkrequests there are still constant calls for `/lightning/list-all-tx?reversed=true` that are basically not needed.

Also when clicking on "Apps" there is just a constant spinner - which could be related to the `subscribe` endpoint sending no messages? @fusion44 is this working on your side in a bitcoin-only mode?
