### ISSUE TITLE
SetupUI sends wrong data when Bitcoin-only

### ISSUE THREAD

**Issue by rootzoll** [cstenglein/raspiblitz-web#325]
I selected Bitcoin only in the setup process but when looking at the final API request the WebUi sends it says `lnd`:
![Bildschirmfoto 2022-06-05 um 10 49 11](https://user-images.githubusercontent.com/2472225/172047489-753fbe5d-15a8-487b-873b-028c198c15f1.png)

**Comment by cstenglein** [comment]
Fixed that 3 Hours ago:
https://github.com/cstenglein/raspiblitz-web/pull/321

Mentioned you as well :O
