### ISSUE TITLE
Disallow hitting send multiple times

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#379]
See https://github.com/fusion44/blitz_api/issues/129#issuecomment-1174684465

**Comment by escapedcat** [comment]
I saw you removed this "count" check in one button. Was that related? Not sure, just a guess.

**Comment by cstenglein** [comment]
No, the submitcount was only that the button is not disabled at the beginning, which I changed, so people don't click on it :D

**Comment by cstenglein** [comment]
ConfirmSendModal does not disable the button when loading. 

Currently on holiday, so will fix it in around two weeks.
