### ISSUE TITLE
Onchain transaction not shown correctly

### ISSUE THREAD

**Issue by fusion44** [cstenglein/raspiblitz-web#383]
![image](https://user-images.githubusercontent.com/503952/180604223-c7cf880f-b995-47a9-9bdd-a923f4c21601.png)

Should be red and not +-123...

**Comment by cstenglein** [comment]
@fusion44 
Can you post the `list-all-tx` response for this transaction please? :)

**Comment by fusion44** [comment]
Oops API problem. Reports it as receive but should be send.
