### ISSUE TITLE
SetupFinal: Do not display seedwords with comma

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#430]
Response from blitz api:

![image](https://user-images.githubusercontent.com/9399034/184937127-f97e38c7-68d7-45fd-a3db-dca811273123.png)

This is also shown in the webui:

![image](https://user-images.githubusercontent.com/9399034/184937183-59d1c126-848d-4001-8c09-9977a1e54a68.png)

Should be cleaned from commas

**Comment by rootzoll** [comment]
If you can remove the comma on the WebUI side that would be best.
