### ISSUE TITLE
Add button in settings to generate debug log

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#49]
~~Need to think how to display that and how many lines etc.~~

~~Need endpoint from https://github.com/fusion44/blitz_api for it~~

Add a button in settings to generate a debug report which can be viewed & downloaded.

**Comment by nyxnor** [comment]
@fusion44 logs meaning the debug logs to be printed, not each service debug log, but this one:
https://github.com/rootzoll/raspiblitz/blob/dev/home.admin/config.scripts/blitz.debug.sh

**Comment by fusion44** [comment]
The script seems to put out a limited number of lines anyway. I'll just return all lines for now. 
If it makes sense, I will make it paged. But for that, I'd have to see the actual output.
I currently can't access my Blitz.

**Comment by nyxnor** [comment]
@fusion44  output example https://termbin.com/gcl0o

**Comment by fusion44** [comment]
Endpoint is in, see my comment in https://github.com/fusion44/blitz_api/issues/18

**Comment by cstenglein** [comment]
Current blocker: #59

**Comment by cstenglein** [comment]
Blocked by https://github.com/fusion44/blitz_api/issues/160

**Comment by cstenglein** [comment]
done
