### ISSUE TITLE
Add validation to send modal

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#50]
The send modal currently has no validation at all.

**Comment by escapedcat** [comment]
Which way of validation would you prefer here and what kind of framework? Or just simple HTML validation for now:  
https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types#client-side_validation

**Comment by cstenglein** [comment]
The logic for the SendModal can be found here:
https://github.com/cstenglein/raspiblitz-web/tree/master/src/components/Shared/SendModal

It got two modes to pay:
(1) You can pay an invoice: 
![image](https://user-images.githubusercontent.com/9399034/137595057-919e80ff-8e24-48ce-abd2-5e038273244d.png)


(2) You can pay on-chain:
![image](https://user-images.githubusercontent.com/9399034/137595075-e98b24cc-1dc5-456d-97ed-ee8bac1940af.png)


And afterwards you have to confirm that choice.

The issue currently with (1) is that the invoice format is not checked (you can write 'Hello world' in it and press 'submit').
The Goal for (1) is to disable the button until a valid invoice is entered (see BOLT#11 [here](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part). It is enough to check for the prefix, i.e. `lnbc`, `lntb`, `lntbs`, or `lnbcrt` IMO.

The issue with (2) is that the address format is not checked. In addition, you could enter any amount and it would send the request. 

Goals for (2) would be to check the address format (same as before, just check the prefix & also allow testnet addresses) + check if the amount is higher than the balance. 

For the extended validation of lightning invoices (enough balance left + invoice still valid) i created #64 so that is not part of the issue.

**Comment by escapedcat** [comment]
Do you have any preference for a (react) validation library? Or fstart with plain HTML validation?

**Comment by escapedcat** [comment]
Ok, will have a look.  
Just wanted to ask because from my experience later on a validation library with more features can be helpful. But that can also be added later. Might be different in the React world anyways.

**Comment by cstenglein** [comment]
Sure, as I said no worries :)

For `yarn audit` to work properly I will have to move some `dependencies` to `devDependencies`

e.g. react-scripts facebook/create-react-app#11174

For better clarification, I'll also add something to contributing or so. Thank you for your input :) :+1:

**Comment by cstenglein** [comment]
Yeah, created #70 for it :+1:
