### ISSUE TITLE
WebUI shows loading animation for unauthorized

### ISSUE THREAD

**Issue by ChuckNorrison** [cstenglein/raspiblitz-web#513]
The WebUI shows the loading animation after a while unused. In the blitzapi logs we can find the entry 

> "GET /sse/subscribe HTTP/1.0" 401 Unauthorized

Logout and login solved it

**Comment by ChuckNorrison** [comment]
I think this happens when nginx gets restarted

**Comment by cstenglein** [comment]
Thank you for the report! Will look at it :)
