### ISSUE TITLE
Rename "Connection Details" to something more fitting & add more fields

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#52]
Currently the ConnectionCard says "Connection Details"

![image](https://user-images.githubusercontent.com/9399034/143771200-a3e42465-93bb-431b-b53a-14d488414ddd.png)

This does not indicate correctly to *what* we can connect there. 

It should indicate better that we can get the tor/local address to the webui there.

**Comment by escapedcat** [comment]
What would be a better name? :P
