### ISSUE TITLE
v1.9.0rc1 Error: reading 'system_temp

### ISSUE THREAD

**Issue by The34Goon** [cstenglein/raspiblitz-web#560]
Web-UI isn't happy.
Brave: TypeError: s is undefined
Fox: TypeError: Cannot read properties of undefined (reading 'system_temp')

Raspiblitz: v1.9.0rc1 (no hickups in SSH, only Web-UI)

Stack trace:

X@http://192.168.0.144/static/js/800.ea1bf8e5.chunk.js:1:15281 div article main qe@http://192.168.0.144/static/js/800.ea1bf8e5.chunk.js:1:52276 Re@http://192.168.0.144/static/js/main.13e331b2.js:2:457789 De@http://192.168.0.144/static/js/main.13e331b2.js:2:458253 Suspense T@http://192.168.0.144/static/js/main.13e331b2.js:2:319505 H@http://192.168.0.144/static/js/main.13e331b2.js:2:321775 Je@http://192.168.0.144/static/js/main.13e331b2.js:2:462826 6812/n.ZP@http://192.168.0.144/static/js/main.13e331b2.js:2:1662 1723/n.ZP@http://192.168.0.144/static/js/main.13e331b2.js:2:3628 Z@http://192.168.0.144/static/js/main.13e331b2.js:2:321019 c@http://192.168.0.144/static/js/main.13e331b2.js:2:438191 t@http://192.168.0.144/static/js/main.13e331b2.js:2:464961 a@http://192.168.0.144/static/js/main.13e331b2.js:2:414652

**Comment by cstenglein** [comment]
Thanks for the report @The34Goon 

Got a fix locally, will write some more tests and push it in the coming days!
