### ISSUE TITLE
Raspiblitz Api + WebUI Problem

### ISSUE THREAD

**Issue by Bimax0815** [cstenglein/raspiblitz-web#581]
nach deaktivieren und wieder aktivieren im Menü, kommt folgende Meldung

ChunkLoadError: Fehler beim Laden von Block 682. (fehlt: http://192.168.0.86/static/js/682.53fc34c6.chunk.js)

Stapelüberwachung:

am Ce (http://192.168.0.86/static/js/main.956ef955.js:2:463585) in Ne 
(http://192.168.0.86/static/js/main.956ef955.js:2:464049) bei Suspense bei B 
(http://192.168.0.86/static/js/main.956ef955.js:2:329207) bei H
(http://192.168.0.86/static/js/main.956ef955.js:2:331742) bei QE
(http://192.168.0.86/static/js/main.956ef955.js:2:468061) bei n.ZP 
(http://192.168.0.86/static/js/main.956ef955.js:2:1664) bei n.ZP 
(http://192.168.0.86/static/js/main.956ef955.js:2:3628) bei Z 
(http://192.168.0.86/static/js/main.956ef955.js:2:330986) bei C 
(http://192.168.0.86/static/js/main.956ef955.js:2:446538) bei t 
(http://192.168.0.86/static/js/main.956ef955.js:2:470196) bei einem 
(http://192.168.0.86/static/js/main.956ef955.js:2:423093)

**Comment by cstenglein** [comment]
Hallo @Bimax0815, danke für die Meldung!

Könntest du bitte deinen Browser Cache löschen und es nochmal probieren? 
Der Fehler deutet darauf hin, dass du eine alte Version im Browser Cache hast.

**Comment by Bimax0815** [comment]
Moin, so Cashe Daten gelöscht. Jetzt kommt folgende Meldung.Es ist mir ein Rätsel 😞LGBimaxAm 11.03.2023 um 16:01 schrieb Christoph Stenglein ***@***.***>:﻿
Hallo @Bimax0815, danke für die Meldung!
Könntest du bitte deinen Browser Cache löschen und es nochmal probieren?
Der Fehler deutet darauf hin, dass du eine alte Version im Browser Cache hast.

**Comment by Bimax0815** [comment]
![10ABC621-4582-424E-A7DA-5115D27EEA06](https://user-images.githubusercontent.com/127603491/224539170-937c3255-9591-4b51-a94a-6512af17617f.png)

**Comment by cstenglein** [comment]
Hi,
entschuldige die späte Antwort. Das ist noch ein Fehler, der von der blitz_api kommt und in Arbeit ist:

https://github.com/fusion44/blitz_api/issues/125

Ich schließe den Issue mal. Wenn du noch Fragen / Anregungen / Probleme hast, mach einfach einen neuen Issue auf :)
