### ISSUE TITLE
The lnbits app link does not change to an onion url

### ISSUE THREAD

**Issue by jalbstmeijer** [cstenglein/raspiblitz-web#614]
When accessing raspiblitz-web through Tor, the  lnbits app link keeps pointing to the local lan ip instead of the onion address.

**Comment by jalbstmeijer** [comment]
@cstenglein 

Just the one supplied with RaspiBlitz:-1.8.0c

RaspiBlitz: 1.8.0
RaspiBlitz WebUI: 1.0.0

**Comment by cstenglein** [comment]
Hi, this was not implemented with 1.8.0, but will be released with 1.9.0 :)

Closing this for now, if it appears on 1.9.0, then it's an issue.
