### ISSUE TITLE
RaspiBlitz:  'insertBefore' auf 'Node'

### ISSUE THREAD

**Issue by Ice2345Ice** [cstenglein/raspiblitz-web#633]
Es wird das Image raspiblitz-fat-v1.9.0-2023-05-22.img.gz verwendet.

Folgende Fehlermeldung erscheint bei der Installation, direkt nach Eingabe des angeforderten Passworts für das Lightning Wallet.

Es ist ein Fehler aufgetreten

NotFoundError: Fehler beim Ausführen von 'insertBefore' auf 'Node': Der Knoten, vor dem der neue Knoten eingefügt werden soll, ist kein untergeordnetes Element dieses Knotens.
Bitte melden Sie diesen Fehler an https://github.com/cstenglein/raspiblitz-web/issues
Stapelüberwachung:
bei n bei div at-Taste bei x (http://192.168.178.34/assets/ButtonWithSpinner-87cd5971.js:1:764) in der Form bei div beim Artikel bei div in der Sektion bei div bei div am Main bei J (http://192.168.178.34/assets/index-a059b434.js:1:415) bei Xe (http://192.168.178.34/assets/index-a059b434.js:1:15801) an einem (http://192.168.178.34/assets/index-b1052a2a.js:40:30832) bei Y_ (http://192.168.178.34/assets/index-b1052a2a.js:84:13130) bei Suspense bei L1 (http://192.168.178.34/assets/index-b1052a2a.js:58:4027) bei B1 (http://192.168.178.34/assets/index-b1052a2a.js:58:6702) an einem (http://192.168.178.34/assets/index-b1052a2a.js:40:30832) bei H_ (http://192.168.178.34/assets/index-b1052a2a.js:84:5951) an einem (http://192.168.178.34/assets/index-b1052a2a.js:40:30832) bei J1 (http://192.168.178.34/assets/index-b1052a2a.js:58:6136) an der M1 (http://192.168.178.34/assets/index-b1052a2a.js:67:713) an einem (http://192.168.178.34/assets/index-b1052a2a.js:40:30832) an einem (http://192.168.178.34/assets/index-b1052a2a.js:68:3231)

Wie kann das Problem behoben werden?

**Comment by cstenglein** [comment]
Am besten probierst du mal deinen Cache zu leeren, sieht so aus als hättest du ein Update etc gemacht und dein Browser versucht noch eine alte Version vom WebUI zu laden.

**Comment by cstenglein** [comment]
Ich schließe den Issue mal, sollte mit der nächsten Version von RaspiBlitz dann nicht mehr auftauchen :)
