### ISSUE TITLE
Add validation checks for lightning invoices on confirm send

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#64]
~~This is blocked until #59 is finished.~~

In the confirm part of the send modal [ConfirmSendModal](https://github.com/cstenglein/raspiblitz-web/blob/master/src/components/Shared/SendModal/ConfirmSendModal/ConfirmSendModal.tsx) it lists all the data of the decoded lightning invoice. 

If the expiry date of the invoice has passed or the amount of the invoice is higher than the available balance, do not enable the confirm button and also write the reason somewhere why the invoice can not be confirmed.

**Comment by escapedcat** [comment]
> If the expiry date of the invoice has passed

```
      timestamp: 1633322501,
      expiry: 36000,
```
To check the invoice is expired it's more or less `[timestamp + expiry] < current_timestamp` (both on matching format), yes?

**Comment by cstenglein** [comment]
> To check the invoice is expired it's more or less [timestamp + expiry] < current_timestamp (both on matching format), yes?

Yes. Handling the edge case of trying to pay too close to expiry is not necessary IMO.
