### ISSUE TITLE
Document development with blitz_api

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#68]
Describe how to develop with polar & blitz_api

**Comment by escapedcat** [comment]
Just adding the link here: https://github.com/jamaljsr/polar

**Comment by escapedcat** [comment]
Is there an existing API-documentation for the blitz-API? Some sort of i.e. [swaggger](https://swagger.io/)

**Comment by cstenglein** [comment]
Yes, I'll finish the issue today so there is documentation on that side :)

**Comment by cstenglein** [comment]
@escapedcat blitz_api provides a swagger interface (built int fastapi)

For info on it see https://github.com/fusion44/blitz_api
