### ISSUE TITLE
Document how to handle dependencies

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#69]
Document that we shoudn't use dependencies for small things to not have too many of them.

**Comment by escapedcat** [comment]
> Document that we shoudn't use dependencies for small things to not have too many of them.

Only noticed now that this issue wasn't about updating deps. Sorry.

**Comment by cstenglein** [comment]
No worries, still a good idea so we don't have to do updates by hand all the time. ;)

**Comment by escapedcat** [comment]
btw thsi is how a depfu PR looks like:  
https://github.com/getAlby/lightning-browser-extension/pull/573

**Comment by cstenglein** [comment]
I think we automated updates & shouldn't be an issue anymore
