### ISSUE TITLE
Clean up Routing & migrate to react-router v6

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#91]
Migration Guide:
https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by escapedcat** [comment]
Tried it for fun, got stuck at "You cannot render a <Router> inside another <Router>. You should never have more than one in your app". Might try again.

**Comment by cstenglein** [comment]
Yeah, I tried it yesterday as well but stopped up for now since there are higher priorities :) (Got the same error btw).

**Comment by cstenglein** [comment]
Could also be a interesting Guide:
https://www.youtube.com/watch?v=zEQiNFAwDGo
