### ISSUE TITLE
TransactionList: Show if a tx is confirmed / unconfirmed

### ISSUE THREAD

**Issue by cstenglein** [cstenglein/raspiblitz-web#95]
Currently, I can't see the difference between unconfirmed & confirmed transactions, except I click on the transaction to see the details.

**Comment by escapedcat** [comment]
Is this still open?

![image](https://user-images.githubusercontent.com/1016218/206860712-4c20f8e3-9ad1-4866-814f-77f5427419a1.png)
This "status: failed" is reflected in the icon, no? Via: https://github.com/cstenglein/raspiblitz-web/blob/master/src/pages/Home/TransactionCard/CategoryIcon.tsx#L33

Or is this about something else?

**Comment by cstenglein** [comment]
Yes, still open :)

The code you mentioned is for lightning transactions, see https://github.com/cstenglein/raspiblitz-web/blob/master/src/pages/Home/TransactionCard/CategoryIcon.tsx#L25

Otherwise I can't see in the TransactionList, if my onChain Tx is confirmed (bonus: if confirmed, show how many confirmations). I played a bit around but haven't found something I'm happy with.

**Comment by escapedcat** [comment]
Ah, it's about on-chain, got it.  
What's the `status` for a unconfirmed on-chain tx?  
Could the `in_flight`-icon work for this as well?

>  show how many confirmations

Maybe one ofg these:
- Just add it as plain text into the info in the list
- If the number of confirmations is smaller than ~10 show the number "within" in the `in_flight`-icon inside a smaller bubble/circle (Maybe including a title-text). If it's more than ~10 no need to show it anymore.

**Comment by cstenglein** [comment]
Sorry for overlooking this comment as well

> If the number of confirmations is smaller than ~10 show the number "within" in the in_flight-icon inside a smaller bubble/circle (Maybe including a title-text). If it's more than ~10 no need to show it anymore.

Good idea! Maybe since it's usually 6 confirms we could use that as baseline. 

> Just add it as plain text into the info in the list

You mean like `1 confirmation` ? Bitcoin Icons provide Icons for 0 - 6 confirmations, which **could** be better but not sure which solution is better: https://bitcoinicons.com/

**Comment by escapedcat** [comment]
Ah nice
![image](https://user-images.githubusercontent.com/1016218/226656541-2a7fed89-8233-4d98-b997-a74001dd39ef.png)

Will have a look
